Week8/W8D1/Reddit_Clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs, except: [:destroy] do
    resources :posts, only: [:index, :create]
  end
  resources :posts
end

Week8/W8D1/Reddit_Clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  content    :string
#  sub_id     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :sub_id, :user_id, presence: true 

  belongs_to :user
  belongs_to :sub
end

Week8/W8D1/Reddit_Clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :user_id, presence: true 

  belongs_to :user 
  has_many :posts
end

Week8/W8D1/Reddit_Clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password
  after_initialize :ensure_session_token
  validates :username, :password_digest, presence: true 
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :posts
  has_many :subs

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
end

Week8/W8D1/Reddit_Clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :login!, :require_login, :logged_in?, :logout, :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logout
    self.current_user.reset_session_token!
    session[:session_token] = nil
  end

end

Week8/W8D1/Reddit_Clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login
  
  def new 
    @post = Post.new 
  end

  def index
    @posts = Post.all
  end

  def create 
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save 
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = @post.errors.full_messages
      render :new 
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])  
    @post.sub_id = params[:sub_id]
    if @post.update(post_params)
       redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit 
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy 
    render :new
  end      
end

Week8/W8D1/Reddit_Clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    user = User.new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login!(user)
      redirect_to #something
    else
      flash[:errors] = @user.errors.full_messages
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

Week8/W8D1/Reddit_Clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.user_id = current_user.id
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

Week8/W8D1/Reddit_Clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to #something
    else
      flash[:errors] = @user.errors.full_messages
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Week8/W8D1/Reddit_Clone/app/helpers/posts_helper.rb
module PostsHelper
end

Week8/W8D1/Reddit_Clone/app/helpers/subs_helper.rb
module SubsHelper
end

Week8/W8D1/Reddit_Clone/app/views/subs/edit.html.erb
<h1>Edit Subreddit</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="_method" value="patch">
  <label>
    Edit Title
    <input type="text" name="sub[title]">
  
  </label>
  <label>
    Edit Description
    <input type="text" name="sub[description]">
  
  </label>

  <input type="submit" value="Edit Subreddit">

</form>

Week8/W8D1/Reddit_Clone/app/views/subs/index.html.erb
<h1>I AM THE INDEX</h1>
<h2>My Subreddits</h2>
<% @subs.each do |sub| %>
  <ul>
    <li><%= sub.title %></li>
    <li><%= sub.description %></li>
  </ul>
<% end %>

Week8/W8D1/Reddit_Clone/app/views/subs/new.html.erb
<h1>New Subreddit</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>
    Title
    <input type="text" name="sub[title]">
  
  </label>
  <label>
    Description
    <input type="text" name="sub[description]">
  
  </label>

  <input type="submit" value="Create Subreddit">

</form>

Week8/W8D1/Reddit_Clone/app/views/subs/show.html.erb
<h1>I AM THE SHOW PAGE</h1>
<ul>
  <li><%= @sub.title %></li>
  <li><%= @sub.description %></li>
</ul>



<h1>New Post</h1>

<form action="<%= sub_posts_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="post[sub_id]" value="<%= @sub.id %>"> 
  <label>
    Title
    <input type="text" name="post[title]">
  
  </label>
  <label>
    URL
    <input type="text" name="post[url]">
  
  </label>

  <label>
    Content
    <input type="text" name="post[content]">
  
  </label>

  <input type="submit" value="Create Post">

</form>

Week8/W8D1/Reddit_Clone/app/views/users/new.html.erb
<h2>Sing Up</h2>

<form action="<%= users_url %>" method="post">
  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>
    Password
    <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" value="Sign Up">
</form>